{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "21a015c3-e4de-49f4-9855-76feca141180",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pylab as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cb4331c6-4258-4758-acec-2dea3fad3dfd",
   "metadata": {},
   "outputs": [],
   "source": [
    "d = pd.read_csv(\"../../../Group14/data/raw/archive/matchesall2014-2020.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "b3a7cdfb-af2d-4cc6-96ec-f3e6def55ec3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Home Team</th>\n",
       "      <th>Away Team</th>\n",
       "      <th>Score</th>\n",
       "      <th>Home Team Fouls</th>\n",
       "      <th>Home Team Yellow Cards</th>\n",
       "      <th>Home Team Second Yellow Cards</th>\n",
       "      <th>Home Team Red Cards</th>\n",
       "      <th>Away Team Fouls</th>\n",
       "      <th>Away Team Yellow Cards</th>\n",
       "      <th>Away Team Second Yellow Cards</th>\n",
       "      <th>Away Team Red Cards</th>\n",
       "      <th>year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>MAN UTD</td>\n",
       "      <td>SWANSEA</td>\n",
       "      <td>1-2</td>\n",
       "      <td>14.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>20.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>WEST BROM</td>\n",
       "      <td>SUNDERLAND</td>\n",
       "      <td>2-2</td>\n",
       "      <td>18.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>LEICESTER CITY</td>\n",
       "      <td>EVERTON</td>\n",
       "      <td>2-2</td>\n",
       "      <td>16.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>WEST HAM</td>\n",
       "      <td>TOTTENHAM</td>\n",
       "      <td>0-1</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>QPR</td>\n",
       "      <td>HULL CITY</td>\n",
       "      <td>0-1</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2655</th>\n",
       "      <td>ARSENAL</td>\n",
       "      <td>BRIGHTON</td>\n",
       "      <td>2-0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2656</th>\n",
       "      <td>SHEFFIELD UTD</td>\n",
       "      <td>BURNLEY</td>\n",
       "      <td>1-0</td>\n",
       "      <td>11.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2657</th>\n",
       "      <td>LEICESTER CITY</td>\n",
       "      <td>TOTTENHAM</td>\n",
       "      <td>2-4</td>\n",
       "      <td>9.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2658</th>\n",
       "      <td>WEST HAM</td>\n",
       "      <td>SOUTHAMPTON</td>\n",
       "      <td>3-0</td>\n",
       "      <td>5.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2659</th>\n",
       "      <td>LEEDS UTD</td>\n",
       "      <td>WEST BROM</td>\n",
       "      <td>3-1</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>12.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2660 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           Home Team    Away Team Score  Home Team Fouls  \\\n",
       "0            MAN UTD      SWANSEA   1-2             14.0   \n",
       "1          WEST BROM   SUNDERLAND   2-2             18.0   \n",
       "2     LEICESTER CITY      EVERTON   2-2             16.0   \n",
       "3           WEST HAM    TOTTENHAM   0-1             12.0   \n",
       "4                QPR    HULL CITY   0-1             10.0   \n",
       "...              ...          ...   ...              ...   \n",
       "2655         ARSENAL     BRIGHTON   2-0             10.0   \n",
       "2656   SHEFFIELD UTD      BURNLEY   1-0             11.0   \n",
       "2657  LEICESTER CITY    TOTTENHAM   2-4              9.0   \n",
       "2658        WEST HAM  SOUTHAMPTON   3-0              5.0   \n",
       "2659       LEEDS UTD    WEST BROM   3-1             12.0   \n",
       "\n",
       "      Home Team Yellow Cards  Home Team Second Yellow Cards  \\\n",
       "0                        2.0                            0.0   \n",
       "1                        3.0                            0.0   \n",
       "2                        1.0                            0.0   \n",
       "3                        2.0                            1.0   \n",
       "4                        1.0                            0.0   \n",
       "...                      ...                            ...   \n",
       "2655                     0.0                            0.0   \n",
       "2656                     3.0                            0.0   \n",
       "2657                     0.0                            0.0   \n",
       "2658                     0.0                            0.0   \n",
       "2659                     2.0                            0.0   \n",
       "\n",
       "      Home Team Red Cards  Away Team Fouls  Away Team Yellow Cards  \\\n",
       "0                     0.0             20.0                     4.0   \n",
       "1                     0.0              9.0                     1.0   \n",
       "2                     0.0             10.0                     1.0   \n",
       "3                     0.0             10.0                     0.0   \n",
       "4                     0.0             10.0                     2.0   \n",
       "...                   ...              ...                     ...   \n",
       "2655                  0.0              8.0                     0.0   \n",
       "2656                  0.0              1.0                     1.0   \n",
       "2657                  0.0              8.0                     2.0   \n",
       "2658                  0.0              9.0                     3.0   \n",
       "2659                  0.0             12.0                     1.0   \n",
       "\n",
       "      Away Team Second Yellow Cards  Away Team Red Cards  year  \n",
       "0                               0.0                  0.0  2014  \n",
       "1                               0.0                  0.0  2014  \n",
       "2                               0.0                  0.0  2014  \n",
       "3                               0.0                  1.0  2014  \n",
       "4                               0.0                  0.0  2014  \n",
       "...                             ...                  ...   ...  \n",
       "2655                            0.0                  0.0  2020  \n",
       "2656                            0.0                  0.0  2020  \n",
       "2657                            0.0                  0.0  2020  \n",
       "2658                            0.0                  0.0  2020  \n",
       "2659                            0.0                  0.0  2020  \n",
       "\n",
       "[2660 rows x 12 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_subset = d[[\"Home Team\", \"Away Team\", \"Score\", \"Home Team Fouls\", \"Home Team Yellow Cards\",\"Home Team Second Yellow Cards\", \"Home Team Red Cards\", \"Away Team Fouls\", \"Away Team Yellow Cards\", \"Away Team Second Yellow Cards\",\"Away Team Red Cards\", \"year\"]]\n",
    "df_subset = df_subset.dropna()\n",
    "df_subset\n",
    "\n",
    "# Picking only relevant columns\n",
    "\n",
    "# Dropping None and NaN values"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "69533378-8d34-4ddf-b7b7-758c17853bb6",
   "metadata": {},
   "source": [
    "## 3.Procss Data "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "54f603e5-b307-4dc5-bdf2-f8ff60c74533",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Home Team</th>\n",
       "      <th>Away Team</th>\n",
       "      <th>Score</th>\n",
       "      <th>Home Team Fouls</th>\n",
       "      <th>Home Team Yellow Cards</th>\n",
       "      <th>Home Team Second Yellow Cards</th>\n",
       "      <th>Home Team Red Cards</th>\n",
       "      <th>Away Team Fouls</th>\n",
       "      <th>Away Team Yellow Cards</th>\n",
       "      <th>Away Team Second Yellow Cards</th>\n",
       "      <th>Away Team Red Cards</th>\n",
       "      <th>year</th>\n",
       "      <th>Total Yellow Cards</th>\n",
       "      <th>Total Red Cards</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>MAN UTD</td>\n",
       "      <td>SWANSEA</td>\n",
       "      <td>1-2</td>\n",
       "      <td>14.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>20.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "      <td>6.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>WEST BROM</td>\n",
       "      <td>SUNDERLAND</td>\n",
       "      <td>2-2</td>\n",
       "      <td>18.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>LEICESTER CITY</td>\n",
       "      <td>EVERTON</td>\n",
       "      <td>2-2</td>\n",
       "      <td>16.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>WEST HAM</td>\n",
       "      <td>TOTTENHAM</td>\n",
       "      <td>0-1</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2014</td>\n",
       "      <td>3.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>QPR</td>\n",
       "      <td>HULL CITY</td>\n",
       "      <td>0-1</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2014</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2655</th>\n",
       "      <td>ARSENAL</td>\n",
       "      <td>BRIGHTON</td>\n",
       "      <td>2-0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2656</th>\n",
       "      <td>SHEFFIELD UTD</td>\n",
       "      <td>BURNLEY</td>\n",
       "      <td>1-0</td>\n",
       "      <td>11.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2657</th>\n",
       "      <td>LEICESTER CITY</td>\n",
       "      <td>TOTTENHAM</td>\n",
       "      <td>2-4</td>\n",
       "      <td>9.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2658</th>\n",
       "      <td>WEST HAM</td>\n",
       "      <td>SOUTHAMPTON</td>\n",
       "      <td>3-0</td>\n",
       "      <td>5.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2659</th>\n",
       "      <td>LEEDS UTD</td>\n",
       "      <td>WEST BROM</td>\n",
       "      <td>3-1</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>12.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2660 rows × 14 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           Home Team    Away Team Score  Home Team Fouls  \\\n",
       "0            MAN UTD      SWANSEA   1-2             14.0   \n",
       "1          WEST BROM   SUNDERLAND   2-2             18.0   \n",
       "2     LEICESTER CITY      EVERTON   2-2             16.0   \n",
       "3           WEST HAM    TOTTENHAM   0-1             12.0   \n",
       "4                QPR    HULL CITY   0-1             10.0   \n",
       "...              ...          ...   ...              ...   \n",
       "2655         ARSENAL     BRIGHTON   2-0             10.0   \n",
       "2656   SHEFFIELD UTD      BURNLEY   1-0             11.0   \n",
       "2657  LEICESTER CITY    TOTTENHAM   2-4              9.0   \n",
       "2658        WEST HAM  SOUTHAMPTON   3-0              5.0   \n",
       "2659       LEEDS UTD    WEST BROM   3-1             12.0   \n",
       "\n",
       "      Home Team Yellow Cards  Home Team Second Yellow Cards  \\\n",
       "0                        2.0                            0.0   \n",
       "1                        3.0                            0.0   \n",
       "2                        1.0                            0.0   \n",
       "3                        2.0                            1.0   \n",
       "4                        1.0                            0.0   \n",
       "...                      ...                            ...   \n",
       "2655                     0.0                            0.0   \n",
       "2656                     3.0                            0.0   \n",
       "2657                     0.0                            0.0   \n",
       "2658                     0.0                            0.0   \n",
       "2659                     2.0                            0.0   \n",
       "\n",
       "      Home Team Red Cards  Away Team Fouls  Away Team Yellow Cards  \\\n",
       "0                     0.0             20.0                     4.0   \n",
       "1                     0.0              9.0                     1.0   \n",
       "2                     0.0             10.0                     1.0   \n",
       "3                     0.0             10.0                     0.0   \n",
       "4                     0.0             10.0                     2.0   \n",
       "...                   ...              ...                     ...   \n",
       "2655                  0.0              8.0                     0.0   \n",
       "2656                  0.0              1.0                     1.0   \n",
       "2657                  0.0              8.0                     2.0   \n",
       "2658                  0.0              9.0                     3.0   \n",
       "2659                  0.0             12.0                     1.0   \n",
       "\n",
       "      Away Team Second Yellow Cards  Away Team Red Cards  year  \\\n",
       "0                               0.0                  0.0  2014   \n",
       "1                               0.0                  0.0  2014   \n",
       "2                               0.0                  0.0  2014   \n",
       "3                               0.0                  1.0  2014   \n",
       "4                               0.0                  0.0  2014   \n",
       "...                             ...                  ...   ...   \n",
       "2655                            0.0                  0.0  2020   \n",
       "2656                            0.0                  0.0  2020   \n",
       "2657                            0.0                  0.0  2020   \n",
       "2658                            0.0                  0.0  2020   \n",
       "2659                            0.0                  0.0  2020   \n",
       "\n",
       "      Total Yellow Cards  Total Red Cards  \n",
       "0                    6.0              0.0  \n",
       "1                    4.0              0.0  \n",
       "2                    2.0              0.0  \n",
       "3                    3.0              1.0  \n",
       "4                    3.0              0.0  \n",
       "...                  ...              ...  \n",
       "2655                 0.0              0.0  \n",
       "2656                 4.0              0.0  \n",
       "2657                 2.0              0.0  \n",
       "2658                 3.0              0.0  \n",
       "2659                 3.0              0.0  \n",
       "\n",
       "[2660 rows x 14 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_subset[\"Total Yellow Cards\"] = df_subset[\"Home Team Yellow Cards\"] + df_subset[\"Home Team Second Yellow Cards\"]+ df_subset[\"Away Team Yellow Cards\"] + df_subset[\"Away Team Second Yellow Cards\"]\n",
    "df_subset[\"Total Red Cards\"] = df_subset[\"Home Team Red Cards\"] + df_subset[\"Away Team Red Cards\"]\n",
    "df_subset\n",
    "\n",
    "# Made a new column"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63bb8dfe-0704-4e54-9662-e4cb330e5a0b",
   "metadata": {},
   "source": [
    "## 4. Wrangle Data"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ad2e40e3-829c-421a-854b-1dc3f364f2c9",
   "metadata": {},
   "source": [
    "###### Create a new data frame that only contains relevant to my research question"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e210597-cc2a-4142-b225-9b0244e4301a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
